### ISSUE TITLE
Error when add link-router on parent template

### ISSUE THREAD

**Issue by jesse1983** [charlieduong94/marko-path-router#15]
I have the following routes:
```
const routes = [
  {
    path: '/users',
    component: require('./users'),
    nestedRoutes: [
      { path: '/new', component: require('./users/components/new') },
    ],
  }
];
```
And templates:
```
/users
    /components
        /new
            index.marko
    index.marko
```
After add a router-link on `users/index`:
```
div.container
  if(input.renderBody)
    include(input.renderBody)
  router-link path='/users/new' -- Go to new user
```

When click, console show this message:

`Uncaught Error: Path must be provided to router-link`

**Comment by charlieduong94** [comment]
@jesse1983 Thanks for reporting this. I'll take a look at this later today.

**Comment by charlieduong94** [comment]
So I tried to recreate the issue you encountered and I found that this happens when `router-link`s are rendered within templates that are not tied to component code (whatever you export in `component.js` or whatever is specified in `class {...}` if you are working with single file components). It looks like marko does not retain the input of child components if not rendered within a proper "component", thus causing the issue that you are seeing.

To fix the issue you are seeing, I recommend linking some component code to all templates you pass into the router's routes.

For example, you can add `class {}` to the top of your `users/index` template:

```
class {}
div.container
  if(input.renderBody)
    include(input.renderBody)
  router-link path='/users/new' -- Go to new user
```
 
I should note that, at the moment, this module only supports renderers that have the `getComponent` method (aka tied to some component code, see this [line](https://github.com/charlieduong94/marko-path-router/blob/master/src/components/router/component.js#L137)). I should have made this more clear in the docs and I will update them accordingly.

**Comment by jesse1983** [comment]
Perfect, it's working now!

I try add `class {}` on index.marko and/or export a `component.js`. Both works.

Thanks!
